AASTHA/Controllers/ReportController.cs
using AASTHA.Models;
using AASTHAEntity;
using iTextSharp.text;
using iTextSharp.text.pdf;
using iTextSharp.tool.xml;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using OfficeOpenXml;
using OfficeOpenXml.Style;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;

namespace AASTHA.Controllers
{
    public class ReportController : BaseController
    {
        //
        // GET: /Report/
        AASTHAEntities db = new AASTHAEntities();
        public ActionResult OPD_Report()
        {
            if (Request.Cookies["Role"].Value == "Doctor")
            {
                return View();
            }
            else
            {
                return RedirectToAction("Login", "Admin");
            }
        }
        public string Getall_OPD_Report(string opddate, string fromdate, string todate, string report)
        {
            if (opddate == "")
            {
                opddate = Convert.ToDateTime(DateTime.Now).ToString("dd/MM/yy");
            }
            var data = from temp in db.OPD_Report(report, opddate, fromdate, todate).ToList()
                       select new
                       {
                           temp.opd_Id,
                           temp.opd_receipt_id,
                           temp.full_name,
                           temp.date,
                           temp.case_type,
                           temp.Consult_Charge,
                           temp.USG_Charge,
                           temp.UPT_Charge,
                           temp.Inj_Charge,
                           temp.Other_Charge,
                           temp.Total
                       };
            return JsonConvert.SerializeObject(new { data = data }, new IsoDateTimeConverter() { DateTimeFormat = "dd/MM/yyyy" });
        }
        public ActionResult IPD_Report()
        {
            if (Request.Cookies["Role"].Value == "Doctor")
            {
                return View();
            }
            else
            {
                return RedirectToAction("Login", "Admin");
            }
        }
        public string Getall_IPD_Report(DatatableModel param, string ipddate, string fromdate, string todate, string report)
        {
            if (ipddate == "")
            {
                ipddate = Convert.ToDateTime(DateTime.Now).ToString("dd/MM/yy");
            }
            var data = from temp in db.IPD_Report(report, ipddate, fromdate, todate).ToList()
                       select new
                       {
                           temp.ipd_Id,
                           temp.full_name,
                           temp.dept_name,
                           temp.addmission_date,
                           temp.discharge_date,
                           temp.C1,
                           temp.C2,
                           temp.C3,
                           temp.C4,
                           temp.C5,
                           temp.C6,
                           temp.C7,
                           temp.C8,
                           temp.C9,
                           temp.C10,
                           temp.C11,
                           temp.C12,
                           temp.C13,
                           temp.Bill,
                           temp.Final_Total
                       };
            return JsonConvert.SerializeObject(new { data = data }, new IsoDateTimeConverter() { DateTimeFormat = "dd/MM/yyyy" });
        }
        public ActionResult Statistics()
        {
            return View();
        }
        public ActionResult YearTab()
        {
            var a = (from temp in db.tbl_opd
                     where temp.date.Value.Year != 2013
                     select new { temp.date.Value.Year }).Distinct().OrderByDescending(m => m.Year);
            List<tbl_opd> list = new List<tbl_opd>();

            foreach (var item in a)
            {
                tbl_opd d = new tbl_opd();
                d.case_type = item.Year.ToString();
                list.Add(d);
            }
            return View(list);
        }
        public ActionResult YearTab2()
        {
            var a = (from temp in db.tbl_opd
                     where temp.date.Value.Year != 2013
                     select new { temp.date.Value.Year }).Distinct().OrderByDescending(m => m.Year);
            List<tbl_opd> list = new List<tbl_opd>();

            foreach (var item in a)
            {
                tbl_opd d = new tbl_opd();
                d.case_type = item.Year.ToString();
                list.Add(d);
            }
            return View(list);
        }
        public ActionResult OPD_Statistics()
        {
            //ViewBag.total_patients = db.tbl_opd.Count();
            //ViewBag.total_collction = db.tbl_opd.Sum(m => m.consult_charge + m.usg_charge + m.upt_charge + m.inj_charge + m.other_charge);
            return View(db.Get_OPD_Monthwise_Collection());
        }
        public ActionResult IPD_Statistics()
        {
            //ViewBag.total_patients = db.tbl_Ipd.Count();
            //ViewBag.total_collction = db.tbl_Ipd.Sum(m => m.bill) - db.tbl_Ipd.Sum(m => m.conssesion);
            return View(db.Get_IPD_Monthwise_Collection());
        }

        public ActionResult OPDReport()
        {
            return View();
        }
        public ActionResult AngularOPDReport()
        {
            return View();
        }
        public ActionResult demo()
        {
            return View();
        }
        public string GetOPD_Report(string opddate, string fromdate, string todate, string report)
        {
            if (opddate == "")
            {
                opddate = Convert.ToDateTime(DateTime.Now).ToString("dd/MM/yy");
            }
            var data = db.OPD_Report(report, opddate, fromdate, todate).ToList();
            var summary = db.DateWiseOPD_Collection(report, opddate, fromdate, todate);
            TempData["OPDReportData"] = data;
            return JsonConvert.SerializeObject(new { summary = summary, data = data }, new IsoDateTimeConverter() { DateTimeFormat = "dd/MM/yyyy" });
        }
        public string GetIPD_Report(string ipddate, string fromdate, string todate, string report)
        {
            if (ipddate == "")
            {
                ipddate = Convert.ToDateTime(DateTime.Now).ToString("dd/MM/yy");
            }
            var data = db.IPD_Report(report, ipddate, fromdate, todate).OrderBy(m => m.discharge_date).ToList();
            var summary = db.DateWiseIPD_Collection(report, ipddate, fromdate, todate);
            TempData["IPDReportData"] = data;
            return JsonConvert.SerializeObject(new { summary = summary, data = data }, new IsoDateTimeConverter() { DateTimeFormat = "dd/MM/yyyy" });
        }
        public ActionResult InvoicesList()
        {
            return View();
        }
        public string NumbersToWords(int inputNumber)
        {
            int inputNo = inputNumber;

            if (inputNo == 0)
                return "Zero";

            int[] numbers = new int[4];
            int first = 0;
            int u, h, t;
            System.Text.StringBuilder sb = new System.Text.StringBuilder();

            if (inputNo < 0)
            {
                sb.Append("Minus ");
                inputNo = -inputNo;
            }

            string[] words0 = {"" ,"One ", "Two ", "Three ", "Four ",
            "Five " ,"Six ", "Seven ", "Eight ", "Nine "};
            string[] words1 = {"Ten ", "Eleven ", "Twelve ", "Thirteen ", "Fourteen ",
            "Fifteen ","Sixteen ","Seventeen ","Eighteen ", "Nineteen "};
            string[] words2 = {"Twenty ", "Thirty ", "Forty ", "Fifty ", "Sixty ",
            "Seventy ","Eighty ", "Ninety "};
            string[] words3 = { "Thousand ", "Lakh ", "Crore " };

            numbers[0] = inputNo % 1000; // units
            numbers[1] = inputNo / 1000;
            numbers[2] = inputNo / 100000;
            numbers[1] = numbers[1] - 100 * numbers[2]; // thousands
            numbers[3] = inputNo / 10000000; // crores
            numbers[2] = numbers[2] - 100 * numbers[3]; // lakhs

            for (int i = 3; i > 0; i--)
            {
                if (numbers[i] != 0)
                {
                    first = i;
                    break;
                }
            }
            for (int i = first; i >= 0; i--)
            {
                if (numbers[i] == 0) continue;
                u = numbers[i] % 10; // ones
                t = numbers[i] / 10;
                h = numbers[i] / 100; // hundreds
                t = t - 10 * h; // tens
                if (h > 0) sb.Append(words0[h] + "Hundred ");
                if (u > 0 || t > 0)
                {
                    //if (h > 0 || i == 0) sb.Append("");
                    if (t == 0)
                        sb.Append(words0[u]);
                    else if (t == 1)
                        sb.Append(words1[u]);
                    else
                        sb.Append(words2[t - 2] + words0[u]);
                }
                if (i != 0) sb.Append(words3[i - 1]);
            }
            return sb.ToString().TrimEnd();
        }
        public JsonResult InvoiceCharges_Table(int ipd_id)
        {
            var charges_Table = db.Get_IPD_Charge_Tabele().Where(m => m.IPD_Id == ipd_id);
            return Json(charges_Table, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        [ValidateInput(false)]
        public FileResult Export(string GridHtml)
        {
            using (MemoryStream stream = new MemoryStream())
            {
                StringReader sr = new StringReader(GridHtml);
                Document pdfDoc = new Document(PageSize.A5, 10f, 10f, 20f, 0f);
                PdfWriter writer = PdfWriter.GetInstance(pdfDoc, stream);
                pdfDoc.Open();

AASTHA/Views/Report/BimetricReport.cshtml
@model IEnumerable<AASTHA.Models.Biometric_Report_Result>
@{
    ViewBag.Title = "Manage_Patient";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}
<div class="blockui_rightgrid">
    <table class="table table-bordered">

        <thead>
            <tr>
                <th>
                    No.
                </th>
                <th>
                    Staff Name
                </th>
                <th>
                   Punching Date Time
                </th> 
                <th>
                    Punching In Time
                </th> 
                <th>
                    Punching Out Time
                </th>              
            </tr>
        </thead>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                   @item.Tran_MachineRawPunchId
                </td>
                <td>
                  @item.username
                </td>
                <td>
                   @item.PunchDatetime
                </td>              
            </tr>
        }

    </table>
</div>

AASTHA/Views/Report/IPD_Statistics.cshtml
@model IEnumerable<AASTHA.Models.Get_IPD_Monthwise_Collection_Result>

@{
    ViewBag.Title = "OPD_Statistics";
    Layout = null;
}

<div class="panel panel-primary" data-collapsed="0">
    <div class="panel-heading">
        <div class="panel-title">
            IPD Statistics
        </div> <div class="panel-options"> <a href="#sample-modal" data-toggle="modal" data-target="#sample-modal-dialog-1" class="bg"><i class="entypo-cog"></i></a> <a href="#" data-rel="collapse"><i class="entypo-down-open"></i></a> <a href="#" data-rel="reload"><i class="entypo-arrows-ccw"></i></a> <a href="#" data-rel="close"><i class="entypo-cancel"></i></a> </div>
    </div>
    <div class="panel-body">
        @Html.Action("YearTab2", "Report")

        <div class="tab-content">

            @foreach (var group in Model.GroupBy(m => m.Dates))
            {
                var id =  Convert.ToInt32(group.Key) + "_" + 2;

                <div id="@id" class="tab-pane fade in">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>
                                    Month
                                </th>
                                <th>
                                    No of Patients
                                </th>
                                <th>
                                    Total Collection
                                </th>

                            </tr>
                        </thead>


                        @foreach (var item in group)
                        {
                            <tr>
                                <td>

                                    @Html.DisplayFor(modelItem => item.Months)
                                </td>

                                <td>
                                    @Html.DisplayFor(modelItem => item.No_of_Patients)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Total_Collection)
                                </td>
                            </tr>
                        }
                        <tfoot>
                            <tr>
                                <td>Total</td>
                                <td>@group.Select(m => m.No_of_Patients).Sum()</td>
                                <td>@group.Select(m => m.Total_Collection).Sum()</td>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            }
        </div>
    </div>
</div>

AASTHA/Views/Report/OPD_Report.cshtml
<link rel="stylesheet" href="~/Content/js/icheck/skins/square/_all.css" id="style-resource-2">

<div ng-app="mainApp" ng-controller="MainController" data-ng-init="getreport()">
    <div class="row">
        <div class="col-md-5">
            <div class="form-group">
                <label for="field-4" class="control-label">Report Type</label>
                <ul class="icheck-list">
                    <li>
                        <input class="icheck-11" type="radio" name="report" value="Daily" checked>
                        <label for="minimal-radio-1-11">Daily Report</label>
                    </li>
                    <li>
                        <input tabindex="8" class="icheck-11" name="report" type="radio" value="Range">
                        <label for="minimal-radio-2-11">Date Range Report</label>
                    </li>
                    <li>
                        <input tabindex="8" class="icheck-11" name="report" type="radio" value="Monthly" />
                        <label for="minimal-radio-2-11">Monthly Report</label>
                    </li>
                </ul>
            </div>
        </div>
        @*<div class="col-md-1 pull-right" ng-if="patients.length != 0">
            <div class="form-group" style="margin-top:25px;">
                <input type="button" class="btn btn-info" value="Print" id="btnprint" ng-click="print()" />
            </div>
        </div>*@
        <div class="col-md-2 pull-right" ng-if="patients.length != 0">
            <div class="form-group" style="margin-top:25px;">
                <div class="input-group-btn">
                    <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown">
                        Print <span class="caret"></span>
                    </button> <ul class="dropdown-menu dropdown-blue">
                        <li><a href="#" ng-click="print()">Report</a></li>
                        <li><a href="@Url.Action("ExportOPD","Report")">Export Excel</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-md-1 pull-right">
            <div class="form-group" style="margin-top:25px;">
                <input type="button" class="btn btn-primary" value="Submit" id="btnreport" ng-click="getreport()" />
            </div>
        </div>

        <div id="daily">
            <div class="col-md-3 pull-right">
                <div class="form-group">
                    <label for="field-4" class="control-label">OPD Date</label>
                    <input type="text" class="form-control datepicker" id="opddate">
                </div>
            </div>
        </div>

        <div id="range">
            <div class="col-md-2 pull">
                <div class="form-group">
                    <label for="field-4" class="control-label">From OPD Date</label>
                    <input type="text" class="form-control datepicker" id="fromdate">
                </div>
            </div>
            <div class="col-md-2 pull">
                <div class="form-group">
                    <label for="field-4" class="control-label">To OPD Date</label>
                    <input type="text" class="form-control datepicker" id="todate">
                </div>
            </div>
        </div>
    </div>
    <hr />

    <ul class="nav nav-tabs">
        <li><a data-toggle="tab" href="#summary">OPD Summary</a></li>
        <li class="active"><a data-toggle="tab" href="#report">OPD Report</a></li>
    </ul>

    <div class="tab-content">
        <div id="summary" class="tab-pane fade">
            <h3 style="text-align:center">OPD Report Summary</h3>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>Date</th>
                        <th>No of Patients</th>
                        <th>Total Collection</th>
                    </tr>
                </thead>
                <tbody>
                    <tr ng-repeat="item in summary">
                        <td>{{item.date}}</td>
                        <td>{{item.No_of_Patients}}</td>
                        <td>{{item.Total_Collection}}</td>
                    </tr>
                </tbody>
                <tr ng-if="summary.length == 0">
                    <td colspan="3" style="text-align:left">No Record Found</td>
                </tr>
                <tfoot ng-if="summary.length != 0" class="tablefooter">
                    <tr>
                        <td>Total</td>
                        <td>{{summarytotal('No_of_Patients')}}</td>
                        <td>{{summarytotal('Total_Collection')}}</td>
                    </tr>
                </tfoot>
            </table>
        </div>
        <div id="report" class="tab-pane fade in active">
            <h3 style="text-align:center">OPD Report</h3>

            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>Invoice No</th>
                        <th>OPD Id</th>
                        <th>Patient's Name</th>
                        <th>Type</th>
                        <th>Cons</th>
                        <th>USG</th>
                        <th>UPT</th>
                        <th>Inj</th>
                        <th>Other</th>
                        <th>Total</th>
                    </tr>
                </thead>
                <tbody ng-repeat="(grpkey, value) in patients | groupBy: 'date'">
                    <tr class="tabletitle">
                        <td colspan="4" style="text-align:center">Date: {{ grpkey }}</td>
                        <td colspan="6" style="text-align:center">{{groupcount(grpkey)}} Patients</td>
                    </tr>
                    <tr ng-repeat="item in value">
                        <td>{{ item.opd_Id }}</td>
                        <td>{{ item.opd_receipt_id }}</td>
                        <td>{{ item.full_name }}</td>
                        <td>{{ item.case_type }}</td>
                        <td>{{ item.Consult_Charge }}</td>
                        <td>{{ item.USG_Charge }}</td>
                        <td>{{ item.UPT_Charge }}</td>
                        <td>{{ item.Inj_Charge }}</td>
                        <td>{{ item.Other_Charge }}</td>
                        <td>{{ item.Total }}</td>
                    </tr>
                    <tr class="tabletitle">
                        <td colspan="3"></td>
                        <td style="text-align:right">Total</td>
                        <td>{{grouptotal(grpkey,'Consult_Charge')}}</td>
                        <td>{{grouptotal(grpkey,'USG_Charge')}}</td>
                        <td>{{grouptotal(grpkey,'UPT_Charge')}}</td>
                        <td>{{grouptotal(grpkey,'Inj_Charge')}}</td>
                        <td>{{grouptotal(grpkey,'Other_Charge')}}</td>
                        <td>{{grouptotal(grpkey,'Total')}}</td>
                    </tr>
                </tbody>
                <tr ng-if="patients.length == 0">
                    <td colspan="11" style="text-align:left">No Record Found</td>
                </tr>
                <tfoot ng-if="patients.length != 0" class="tablefooter">
                    <tr>
                        <td colspan="3">{{patients.length}} Patients</td>
                        <td style="text-align:right">Grand Total</td>
                        <td>{{total('Consult_Charge')}}</td>
                        <td>{{total('USG_Charge')}}</td>
                        <td>{{total('UPT_Charge')}}</td>
                        <td>{{total('Inj_Charge')}}</td>
                        <td>{{total('Other_Charge')}}</td>
                        <td>{{total('Total')}}</td>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>

    <!-- Modal -->
    <div id="myModal" class="modal fade" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Send Report</h4>
                </div>
                <div class="modal-body">
                    <form action="/action_page.php">
                        <div class="form-group">
                            <label for="email">Email address:</label>
                            <input type="email" class="form-control" id="email">
                        </div>
                        <div class="form-group">
                            <label for="pwd">Password:</label>
                            <input type="password" class="form-control" id="pwd">
                        </div>
                        <div class="checkbox">
                            <label><input type="checkbox"> Remember me</label>
                        </div>
                        <button type="submit" class="btn btn-default">Submit</button>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>

        </div>
    </div>
</div>

<script src="~/Scripts/angular.min.js"></script>
<script src="~/Scripts/angular-filter.js"></script>
<script src="~/Content/js/bootstrap-datepicker.js"></script>
<script src="~/Scripts/jQuery.print.js"></script>
<script src="~/Content/js/icheck/icheck.min.js"></script>

<script>
    $('input.icheck-11').iCheck({
        radioClass: 'iradio_square-blue'
    });
    var activeTab = "#report";
    $('a[data-toggle="tab"]').on('shown.bs.tab', function (e) {
        activeTab = $(e.target).attr('href');
    });
    $("#range").hide();
    $('input').on('ifClicked', function (ev) {
        if (this.value == 'Daily') {
            $("#range").hide();
            $("#daily").show();
        }
        else if (this.value == 'Range') {
            $("#daily").hide();
            $("#range").show();
        }
        else {
            $("#range").hide();
            $("#daily").show();
        }
    });
    $("#btnSubmit").click(function () {
        $("input[name='GridHtml']").val($("#summary").html());
    });
    angular.module('mainApp', ['angular.filter'])
        .controller('MainController', function ($scope, $http) {
            $scope.getreport = function () {
                blockui();
                var opddate = $("#opddate").val();
                var fromdate = $("#fromdate").val();
                var todate = $("#todate").val();
                var reporttype = $("input[name='report']:checked").val();
                $http.get(
                    "GetOPD_Report/Report",
                    { params: { opddate: opddate, fromdate: fromdate, todate: todate, report: reporttype } })
                    .success(function (response) {
                        unblockui();
                        $scope.patients = response.data;
                        $scope.summary = response.summary;
                        $scope.summarytotal = function (key) {
                            var total = 0;
                            for (var i = 0; i < $scope.summary.length; i++) {
                                var opd = $scope.summary[i];
                                total += (opd[key]);
                            }
                            return total;
                        }
                        $scope.groupcount = function (group) {
                            var total = 0;
                            for (var i = 0; i < $scope.patients.length; i++) {
                                var opd = $scope.patients[i];
                                if (opd.date == group) {
                                    total += 1;
                                }
                            }
                            return total;
                        }
                        $scope.total = function (key) {
                            var total = 0;
                            for (var i = 0; i < $scope.patients.length; i++) {
                                var opd = $scope.patients[i];
                                total += (opd[key]);
                            }
                            return total;
                        }
                        $scope.grouptotal = function (group, key) {
                            var total = 0;
                            for (var i = 0; i < $scope.patients.length; i++) {
                                var opd = $scope.patients[i];
                                if (opd.date == group) {
                                    total += (opd[key]);
                                }
                            }
                            return total;
                        }
                    });
            }
            $scope.print = function () {
                $(activeTab).print();
            }
        });
</script>
<style>
    .icheck-list > li {
        display: inline;
        margin-bottom: 10px;
    }


    .datatable_loader {
        position: fixed;
        left: 0px;
        top: 0px;
        width: 100%;
        height: 100%;
        z-index: 9999;
        background: url('../Content/loader.gif') 50% 50% no-repeat rgba(249,249,249,.7);
    }

    .table > thead > tr > th, .table > tbody > tr > th, .table > tfoot > tr > th, .table > thead > tr > td, .table > tbody > tr > td, .table > tfoot > tr > td {
        padding: 4px;
    }

    table thead tr th {
        font-size: 12px;
    }

    td {
        font-size: 12px;
    }

    .copyButton {
        background: #ff0000;
    }

    .tabletitle {
        font-weight: bold;
    }

    .tablefooter {
        font-weight: bold;
        text-decoration: underline;
    }
</style>

AASTHA/Views/Report/OPD_Statistics.cshtml
@model IEnumerable<AASTHA.Models.Get_OPD_Monthwise_Collection_Result>

@{
    ViewBag.Title = "OPD_Statistics";
    Layout = null;
}
<div class="panel panel-primary" data-collapsed="0">
    <div class="panel-heading">
        <div class="panel-title">
            OPD Statistics
        </div> <div class="panel-options"> <a href="#sample-modal" data-toggle="modal" data-target="#sample-modal-dialog-1" class="bg"><i class="entypo-cog"></i></a> <a href="#" data-rel="collapse"><i class="entypo-down-open"></i></a> <a href="#" data-rel="reload"><i class="entypo-arrows-ccw"></i></a> <a href="#" data-rel="close"><i class="entypo-cancel"></i></a> </div>
    </div>
    <div class="panel-body">
        @Html.Action("YearTab", "Report")

        <div class="tab-content">

            @foreach (var group in Model.GroupBy(m => m.Dates))
            {
                <div id="@group.Key" class="tab-pane fade in">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>
                                    Month
                                </th>
                                <th>
                                    No of Patients
                                </th>
                                <th>
                                    Total Collection
                                </th>
                            </tr>
                        </thead>


                        @foreach (var item in group)
                        {
                            <tr>
                                <td>

                                    @Html.DisplayFor(modelItem => item.Months)
                                </td>

                                <td>
                                    @Html.DisplayFor(modelItem => item.No_of_Patients)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Total_Collection)
                                </td>
                            </tr>
                        }
                        <tfoot>
                            <tr>
                                <td>Total</td>
                                <td>@group.Select(m=>m.No_of_Patients).Sum()</td>
                                <td>@group.Select(m=>m.Total_Collection).Sum()</td>
                            </tr>
                        </tfoot>
                    </table>
                </div>

            }
        </div>




    </div>
</div>

AASTHA/Views/Report/Statistics.cshtml
<div class="row">
    <div class="col-lg-6">
        @Html.Action("OPD_Statistics", "Report")
    </div>
    <div class="col-lg-6">
        @Html.Action("IPD_Statistics", "Report")
    </div>
</div>

AASTHA/Views/Report/YearTab.cshtml
@model IEnumerable<AASTHA.Models.tbl_opd>
@{
    ViewBag.Title = "YearTab";
    Layout = null;
}
<ul class="nav nav-tabs">
    @foreach (var item in Model)
    {
        <li><a data-toggle="tab" href="#@item.case_type">@item.case_type</a></li>
    }
</ul>
<script>
    $(function () {
        function activaTab(tab) {
            $('.nav-tabs a[href="#' + tab + '"]').tab('show');
        };
        var year = new Date().getFullYear()
        activaTab(year);
    })
   
</script>

AASTHA/Views/Report/YearTab2.cshtml
@model IEnumerable<AASTHA.Models.tbl_opd>
@{
    ViewBag.Title = "YearTab";
    Layout = null;
}
<ul class="nav nav-tabs">
    @foreach (var item in Model)
    {
        var id = item.case_type + "_" + 2;
        <li><a data-toggle="tab" href="#@id">@item.case_type</a></li>
    }
</ul>
<script>
    $(function () {
        function activaTab(tab) {
            $('.nav-tabs a[href="#' + tab + '"]').tab('show');
        };
        var year = (new Date().getFullYear()) + "_" + 2;
        activaTab(year);
    })

</script>

AASTHA/Views/Report/demoreport.cshtml
@{
    ViewBag.Title = "OPD_Report";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}