AASTHA/Controllers/AttendanceController.cs
using AASTHA.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AASTHA.Controllers
{
    public class AttendanceController : BaseController
    {
        //

        // GET: /Attendance/

        AASTHAEntities db = new AASTHAEntities();

        public ActionResult Manage_Attendance()
        {
            var exclude = "ginesh29,bhaumik";
            var user = db.tbl_user.Where(i => !exclude.Contains(i.username)).ToList();
            return View(user);
        }
        [HttpPost]
        public ActionResult Manage_Attendance(List<int> uid, List<string> day1, List<string> day2, List<string> day3, List<string> day4, List<string> day5, List<string> day6, List<string> day7)
        {
            DateTime firstDate = CommonFun.GetFirstDateOfWeek(DateTime.Parse(DateTime.Now.ToString("dd/MM/yyyy")).Date, DayOfWeek.Monday);
            DateTime lastDate = CommonFun.GetLastDateOfWeek(DateTime.Parse(DateTime.Now.ToString("dd/MM/yyyy")).Date, DayOfWeek.Sunday);

            for (int i = 0; i < day1.Count; i++)
            {
                db.Add_Shift(uid[i], firstDate.AddDays(i), day1[i]);
            }

            for (int i = 0; i < day2.Count; i++)
            {
                db.Add_Shift(uid[i], firstDate.AddDays(i), day2[i]);
            }

            for (int i = 0; i < day3.Count; i++)
            {
                db.Add_Shift(uid[i], firstDate.AddDays(i), day3[i]);
            }

            for (int i = 0; i < day4.Count; i++)
            {
                db.Add_Shift(uid[i], firstDate.AddDays(i), day4[i]);
            }
            for (int i = 0; i < day5.Count; i++)
            {
                db.Add_Shift(uid[i], firstDate.AddDays(i), day5[i]);
            }
            for (int i = 0; i < day6.Count; i++)
            {
                db.Add_Shift(uid[i], firstDate.AddDays(i), day6[i]);
            }
            for (int i = 0; i < day7.Count; i++)
            {
                db.Add_Shift(uid[i], firstDate.AddDays(i), day7[i]);
            }
            var exclude = "ginesh29,bhaumik";
            var user = db.tbl_user.Where(i => !exclude.Contains(i.username)).ToList();
            return View(user);
        }

        public ActionResult ImportAttendance()
        {
            return View();
        }
        //public ActionResult Import(HttpPostedFileBase file)
        //{
        //    if (file != null && file.ContentLength > 0)
        //    {
        //        var fileName = Path.GetFileName(file.FileName);
        //        var path = Path.Combine(Server.MapPath("~/Views"), fileName);
        //        file.SaveAs(path);
        //    }
        //    var list = new List<string>();
        //    List<tbl_attendance> lstattendance = new List<tbl_attendance>();
        //    List<tbl_attendance> diff = new List<tbl_attendance>();
        //    using (var stream = new StreamReader(Server.MapPath("~/Views/AGL_001.txt")))
        //    {
        //        string inLine = stream.ReadToEnd();
        //        list = inLine.Split(new string[] { "\r\n" }, StringSplitOptions.None).ToList();
        //        list.RemoveAt(0);

        //        foreach (var s in list)
        //        {
        //            string[] splited = s.Split('\t');
        //            int Id = int.Parse(splited[0]);
        //            int Enroll = int.Parse(splited[2]);
        //            DateTime Date = Convert.ToDateTime(splited[6]);
        //            lstattendance.Add(new tbl_attendance { No = Id, EnNo = Enroll, DateTime = Date });
        //        }
        //        diff = lstattendance.Where(p => !db.tbl_attendance.Any(l => p.No == l.No)).ToList();

        //        foreach (var item in diff)
        //        {
        //            db.Entry(item).State = EntityState.Added;
        //            db.SaveChanges();
        //        }
        //    }
        //    TempData["successmsg"] = diff.Count + " Record added Successfully";
        //    return RedirectToAction("ImportAttendance");
        //}
    }
}

AASTHA/Views/Attendance/ImportAttendance.cshtml
@model AASTHA.Models.PatientModel
@{
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<link href="~/Content/jquery.typeahead.css" rel="stylesheet" />
@Html.Partial("_ResultMEssage")
<div class="panel panel-primary col-lg-6" data-collapsed="0">
    <div class="panel-heading">
        <div class="panel-title">
            Attendance Import Wizard
        </div> <div class="panel-options"> <a href="#sample-modal" data-toggle="modal" data-target="#sample-modal-dialog-1" class="bg"><i class="entypo-cog"></i></a> <a href="#" data-rel="collapse"><i class="entypo-down-open"></i></a> <a href="#" data-rel="reload"><i class="entypo-arrows-ccw"></i></a> <a href="#" data-rel="close"><i class="entypo-cancel"></i></a> </div>
    </div>
    <div class="panel-body">

        @using (Html.BeginForm("Import", "Attendance", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <div class="row">
                <div class="">
                    <div class="form-group">
                        <input type="file" name="file" />
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-info">Save changes</button>
                </div>
            </div>

        }
    </div>
</div>
<div class="clearfix"></div>

AASTHA/Views/Attendance/Manage_Attendance.cshtml
<link rel="stylesheet" href="~/Content/js/icheck/skins/square/_all.css" id="style-resource-2">

<div ng-app="mainApp" ng-controller="MainController" data-ng-init="getreport()">
    <div class="row">
        <div class="col-md-5">
            <div class="form-group">
                <label for="field-4" class="control-label">Report Type</label>
                <ul class="icheck-list">
                    <li>
                        <input class="icheck-11" type="radio" name="report" value="Daily" checked>
                        <label for="minimal-radio-1-11">Daily Report</label>
                    </li>
                    <li>
                        <input tabindex="8" class="icheck-11" name="report" type="radio" value="Range">
                        <label for="minimal-radio-2-11">Date Range Report</label>
                    </li>
                    <li>
                        <input tabindex="8" class="icheck-11" name="report" type="radio" value="Monthly" />
                        <label for="minimal-radio-2-11">Monthly Report</label>
                    </li>
                </ul>
            </div>
        </div>
        <div class="col-md-1 pull-right" ng-if="patients.length != 0">
            <div class="form-group" style="margin-top:25px;">
                <input type="button" class="btn btn-info" value="Print" id="btnprint" ng-click="print()" />
            </div>
        </div>
        <div class="col-md-1 pull-right">
            <div class="form-group" style="margin-top:25px;">
                <input type="button" class="btn btn-primary" value="Submit" id="btnreport" ng-click="getreport()" />
            </div>
        </div>

        <div id="daily">
            <div class="col-md-3 pull-right">
                <div class="form-group">
                    <label for="field-4" class="control-label">OPD Date</label>
                    <input type="text" class="form-control datepicker" id="opddate">
                </div>
            </div>
        </div>

        <div id="range">
            <div class="col-md-2 pull">
                <div class="form-group">
                    <label for="field-4" class="control-label">From OPD Date</label>
                    <input type="text" class="form-control datepicker" id="fromdate">
                </div>
            </div>
            <div class="col-md-2 pull">
                <div class="form-group">
                    <label for="field-4" class="control-label">To OPD Date</label>
                    <input type="text" class="form-control datepicker" id="todate">
                </div>
            </div>
        </div>
    </div>
    <hr />
    <div class="printable">
        <h3 style="text-align:center">OPD Report</h3>

        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Invoice No</th>
                    <th>OPD Id</th>
                    <th>Patient's Name</th>
                    <th>Type</th>
                    <th>Cons</th>
                    <th>USG</th>
                    <th>UPT</th>
                    <th>Inj</th>
                    <th>Other</th>
                    <th>Total</th>
                </tr>
            </thead>
            <tbody ng-repeat="(grpkey, value) in patients | groupBy: 'date'">
                <tr class="tabletitle">
                    <td colspan="4" style="text-align:center">Date: {{ grpkey }}</td>
                    <td colspan="6" style="text-align:center">{{groupcount(grpkey)}} Patients</td>
                </tr>
                <tr ng-repeat="item in value">
                    <td>{{ item.opd_Id }}</td>
                    <td>{{ item.opd_receipt_id }}</td>
                    <td>{{ item.full_name }}</td>
                    <td>{{ item.case_type }}</td>
                    <td>{{ item.Consult_Charge }}</td>
                    <td>{{ item.USG_Charge }}</td>
                    <td>{{ item.UPT_Charge }}</td>
                    <td>{{ item.Inj_Charge }}</td>
                    <td>{{ item.Other_Charge }}</td>
                    <td>{{ item.Total }}</td>
                </tr>
                <tr class="tabletitle">
                    <td colspan="3"></td>
                    <td style="text-align:right">Total</td>
                    <td>{{grouptotal(grpkey,'Consult_Charge')}}</td>
                    <td>{{grouptotal(grpkey,'USG_Charge')}}</td>
                    <td>{{grouptotal(grpkey,'UPT_Charge')}}</td>
                    <td>{{grouptotal(grpkey,'Inj_Charge')}}</td>
                    <td>{{grouptotal(grpkey,'Other_Charge')}}</td>
                    <td>{{grouptotal(grpkey,'Total')}}</td>
                </tr>
            </tbody>
            <tr ng-if="patients.length == 0">
                <td colspan="11" style="text-align:left">No Record Found</td>
            </tr>
            <tfoot ng-if="patients.length != 0" class="tablefooter">
                <tr>
                    <td colspan="3">{{patients.length}} Patients</td>
                    <td style="text-align:right">Grand Total</td>
                    <td>{{total(grpkey,'Consult_Charge')}}</td>
                    <td>{{total(grpkey,'USG_Charge')}}</td>
                    <td>{{total(grpkey,'UPT_Charge')}}</td>
                    <td>{{total(grpkey,'Inj_Charge')}}</td>
                    <td>{{total(grpkey,'Other_Charge')}}</td>
                    <td>{{total(grpkey,'Total')}}</td>
                </tr>
            </tfoot>
        </table>
    </div>
</div>

<script src="~/Scripts/angular.min.js"></script>
<script src="~/Scripts/angular-filter.js"></script>
<script src="~/Content/js/bootstrap-datepicker.js"></script>
<script src="~/Scripts/jQuery.print.js"></script>
<script src="~/Content/js/icheck/icheck.min.js"></script>

<script>
    $('input.icheck-11').iCheck({
        radioClass: 'iradio_square-blue'
    });

    $("#range").hide();
    $('input').on('ifClicked', function (ev) {
        if (this.value == 'Daily') {
            $("#range").hide();
            $("#daily").show();
        }
        else if (this.value == 'Range') {
            $("#daily").hide();
            $("#range").show();
        }
        else {
            $("#range").hide();
            $("#daily").show();
        }
    });
    angular.module('mainApp', ['angular.filter'])
    .controller('MainController', function ($scope, $http) {
        $scope.getreport = function () {
            blockui();
            var opddate = $("#opddate").val();
            var fromdate = $("#fromdate").val();
            var todate = $("#todate").val();
            var reporttype = $("input[name='report']:checked").val();
            $http.get(
            "/Report/GetOPD_Report",
            { params: { opddate: opddate, fromdate: fromdate, todate: todate, report: reporttype } })
             .success(function (response) {
                 unblockui();
                 $scope.patients = response;

                 $scope.groupcount = function (group) {
                     var total = 0;
                     for (var i = 0; i < $scope.patients.length; i++) {
                         var opd = $scope.patients[i];
                         if (opd.date == group) {
                             total += 1;
                         }
                     }
                     return total;
                 }
                 $scope.total = function (group, key) {
                     var total = 0;
                     for (var i = 0; i < $scope.patients.length; i++) {
                         var opd = $scope.patients[i];
                         total += (opd[key]);
                     }
                     return total;
                 }
                 $scope.grouptotal = function (group, key) {
                     var total = 0;
                     for (var i = 0; i < $scope.patients.length; i++) {
                         var opd = $scope.patients[i];
                         if (opd.date == group) {
                             total += (opd[key]);
                         }
                     }
                     return total;
                 }
             });
        }
        $scope.print = function () {
            $(".printable").print();
        }
    });
</script>
<style>
    .icheck-list > li {
        display: inline;
        margin-bottom: 10px;
    }

    #prt-container table {
        border-collapse: collapse;
    }

    #prt-container th,
    #prt-container td {
        border: 1px solid black;
    }

    .datatable_loader {
        position: fixed;
        left: 0px;
        top: 0px;
        width: 100%;
        height: 100%;
        z-index: 9999;
        background: url('../Content/loader.gif') 50% 50% no-repeat rgba(249,249,249,.7);
    }

    .table > thead > tr > th, .table > tbody > tr > th, .table > tfoot > tr > th, .table > thead > tr > td, .table > tbody > tr > td, .table > tfoot > tr > td {
        padding: 4px;
    }

    table thead tr th {
        font-size: 12px;
    }

    td {
        font-size: 12px;
    }

    .copyButton {
        background: #ff0000;
    }

    .tabletitle {
        font-weight: bold;
    }

    .tablefooter {
        font-weight: bold;
        text-decoration: underline;
    }
</style>