AASTHA/Controllers/IPDController.cs
using AASTHA.Models;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;
using System.Collections;
using AASTHAEntity;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace AASTHA.Controllers
{
    public class IPDController : Controller
    {
        AASTHAEntities db = new AASTHAEntities();
        public void Bind_IPD_Type()
        {
            string[] type = { "Delivery", "Operation", "General" };
            ViewBag.IPD_Type_List = type.Select(m => new SelectListItem { Text = m, Value = m });
        }
        public void Bind_Room_Type()
        {
            string[] Room = { "General", "Special", "Semi-Special" };
            ViewBag.Room_Type_List = Room.Select(m => new SelectListItem { Text = m, Value = m });
        }
        public void Bind_Delivery_Type()
        {
            ViewBag.Delivery_Type_List = db.delivery_master.ToList().Select(m => new SelectListItem { Text = m.delivery, Value = m.delivery_typeId.ToString() });
        }
        public void Bind_Baby_Gender()
        {
            string[] Gender = { "Boy", "Girl" };
            ViewBag.Baby_Gender_List = Gender.Select(m => new SelectListItem { Text = m, Value = m });
        }
        public void Bind_Delivery_Diagnosis()
        {
            string[] Delivery_Diagnosis = { "Labour Pain", "Licking P/V" };
            ViewBag.Delivery_Diagnosis_List = Delivery_Diagnosis.Select(m => new SelectListItem { Text = m, Value = m });
        }
        public void Bind_General_Diagnosis()
        {
            ViewBag.General_Diagnosis_List = db.general_diagnosis.ToList().Select(m => new SelectListItem { Text = m.general_diagnosis_name, Value = m.general_diagnosis_Id.ToString() });
        }
        public void Bind_Operation_Diagnosis()
        {
            ViewBag.Operation_Diagnosis_List = db.diagnosis_master.ToList().Select(m => new SelectListItem { Text = m.diagnosis_type, Value = m.diagnosis_type.ToString() });
        }
        public void Bind_Operation_Type()
        {
            ViewBag.Operation_Type_List = db.operation_master.ToList().Select(m => new SelectListItem { Text = m.operation_type, Value = m.operation_typeId.ToString() });
        }
        public ActionResult IPD_Entry()
        {
            if (Request.Cookies["User"] == null)
            {
                return RedirectToAction("Login", "Admin");
            }
            else
            {
                Bind_IPD_Type();
                Bind_Room_Type();
                Bind_Delivery_Type();
                Bind_Baby_Gender();
                Bind_Delivery_Diagnosis();
                Bind_General_Diagnosis();
                Bind_Operation_Diagnosis();
                Bind_Operation_Type();
                return View();
            }
        }
        public ActionResult Modal_Edit(int? ipd_id)
        {
            Bind_IPD_Type();
            Bind_Room_Type();
            Bind_Delivery_Type();
            Bind_Baby_Gender();
            Bind_Delivery_Diagnosis();
            Bind_General_Diagnosis();
            Bind_Operation_Diagnosis();
            Bind_Operation_Type();
            return View();
        }
        public ActionResult Get_IpdType(int? Ipd_Id)
        {
            var type = db.tbl_Ipd.FirstOrDefault(m => m.ipd_Id == Ipd_Id).dept_name;
            return Json(type, JsonRequestBehavior.AllowGet);
        }
        public ActionResult Charges_Table()
        {
            return View(db.IPD_Charges_Master.ToList());
        }
        [HttpPost]
        public ActionResult Modal_Edit(IPDModel model, List<int> Charge_Id, List<float> day, List<int> rate, List<int> amt, int? total, int? Patient_Id, int? Concession)
        {
            try
            {

                var exist = db.tbl_Ipd.FirstOrDefault(c => c.ipd_Id == model.IPD_Id_Edit);
                if (exist == null)
                {
                    if (model.IPD_Type == "Delivery")
                    {
                        string Delivery_Type = string.Join(",", model.Delivery_Type);
                        db.insert_ipd_entry(model.IPD_Type, model.Patient_Id, model.IPD_Id_Edit, model.Room_Type, model.Addmission_Date, model.Discharge_Date, total, Concession, null, null, null, null, model.Delivery_Diagnosis, Delivery_Type, model.Delivery_Date, model.Delivery_Time, model.Baby_Gender, model.Baby_Weight);
                    }
                    else if (model.IPD_Type == "Operation")
                    {
                        string Operation_Diagnosis = string.Join(",", model.Operation_Diagnosis);
                        string Operation_Type = string.Join(",", model.Operation_Type);
                        db.insert_ipd_entry(model.IPD_Type, model.Patient_Id, model.IPD_Id_Edit, model.Room_Type, model.Addmission_Date, model.Discharge_Date, total, Concession, null, Operation_Diagnosis, model.Operation_Date, Operation_Type, null, null, null, null, null, null);
                    }
                    else if (model.IPD_Type == "General")
                    {
                        string General_Diagnosis = string.Join(",", model.General_Diagnosis);
                        db.insert_ipd_entry(model.IPD_Type, model.Patient_Id, model.IPD_Id_Edit, model.Room_Type, model.Addmission_Date, model.Discharge_Date, total, Concession, General_Diagnosis, null, null, null, null, null, null, null, null, null);
                    }
                    for (int i = 0; i < Charge_Id.Count; i++)
                    {
                        db.Insert_IPDCharge_Table(model.IPD_Id_Edit, Charge_Id[i], day[i], rate[i], amt[i]);
                    }
                    TempData["successmsg"] = "Record Inserted Successfully";
                }
                else if (exist != null)
                {
                    if (exist.dept_name == "Delivery")
                    {
                        string Delivery_Type = string.Join(",", model.Delivery_Type);

                        db.edit_delivery_entry(model.IPD_Id_Edit, model.Room_Type, model.Addmission_Date, model.Delivery_Date, model.Delivery_Time, model.Delivery_Diagnosis, Delivery_Type, model.Discharge_Date, model.Baby_Gender, model.Baby_Weight, total, Concession);
                    }
                    else if (exist.dept_name == "Operation")
                    {
                        string Operation_Diagnosis = string.Join(",", model.Operation_Diagnosis);
                        string Operation_Type = string.Join(",", model.Operation_Type);
                        db.edit_operation_entry(model.IPD_Id_Edit, model.Room_Type, model.Addmission_Date, model.Operation_Date, Operation_Diagnosis, Operation_Type, model.Discharge_Date, total, Concession);
                    }
                    else if (exist.dept_name == "General")
                    {
                        string General_Diagnosis = string.Join(",", model.General_Diagnosis);
                        db.edit_general_entry(model.IPD_Id_Edit, model.Room_Type, model.Addmission_Date, General_Diagnosis, model.Discharge_Date, total, Concession);
                    }

                    for (int i = 0; i < Charge_Id.Count; i++)
                    {
                        db.Edit_IPD_Charge_Table(model.IPD_Id_Edit, Charge_Id[i], day[i], rate[i], amt[i]);
                    }
                    TempData["successmsg"] = "Record Updated Successfully";
                }

            }
            catch (Exception ex)
            {
                TempData["errormsg"] = ex.Message;
            }

            return RedirectToAction("IPD_Entry");
        }
        public ActionResult Manage_IPD_Entry()
        {
            if (Request.Cookies["User"] != null)
            {
                if (Request.Cookies["Role"].Value == "Doctor")
                {
                    return View();
                }
                else
                {
                    return RedirectToAction("Login", "Admin");
                }
            }
            else
            {
                return RedirectToAction("Login", "Admin");
            }
        }
        public string Getall_IPD_Entry(GridSettings grid)
        {
            var query = from ipd in db.tbl_Ipd
                        join patient in db.tbl_patient on ipd.patient_id equals patient.patient_Id
                        select new { ipd.ipd_Id, ipd.ipd_receipt_id, patient.full_name, ipd.dept_name, ipd.addmission_date, ipd.discharge_date, ipd.bill, ipd.conssesion };

            int count;
            var data = query.GridCommonSettings(grid, out count);

            var result = new
            {
                total = (int)Math.Ceiling((double)count / grid.PageSize),
                page = grid.PageIndex,
                records = count,
                rows = (from i in data
                        select new
                        {
                            ipd_Id = i.ipd_Id,
                            full_name = i.full_name,
                            dept_name = i.dept_name,
                            addmission_date = i.addmission_date,
                            discharge_date = i.discharge_date,
                            Bill = i.bill ?? 0,
                            Concession = i.conssesion ?? 0,
                            Final_Amount = (i.bill - i.conssesion) ?? 0,
                            action = i.ipd_Id
                        }).ToArray()
            };
            return JsonConvert.SerializeObject(result, new IsoDateTimeConverter() { DateTimeFormat = "dd/MM/yyyy" });
        }
        public ActionResult Charge_Detail()
        {
            return View();
        }
        public ActionResult Fetch_IPD_Details(int? ipd_id, string ipd_type)
        {
            var result = "";
            if (ipd_type == "Delivery")
            {
                var delivery_detail = from ipd in db.tbl_Ipd

AASTHA/Views/IPD/AddEdit_Advice.cshtml
@model AASTHA.Models.AdminModel

@{
    Layout = null;
}

@using (Ajax.BeginForm("AddEdit_Advice", "IPD", new AjaxOptions { UpdateTargetId = "Grid_Advice", OnBegin = "blockui_leftgrid", OnComplete = "unblockui_leftgrid", OnSuccess = "OnSuccess" }))
{
    @Html.Hidden("page")
    <div class="row">
        <div class="col-md-12 textContainer">
            <div class="form-group">
                <div class="input-group"> @Html.TextBoxFor(model => model.Advice_Text, new { @class = "form-control Capitalize", placeholder = "Enter Advice Title" }) <span class="input-group-btn"> <input class="btn btn-primary btnadd" type="submit" value="Save Changes"></span> </div>
                @Html.ValidationMessageFor(m => m.Advice_Text)
            </div>
        </div>
    </div>
}

AASTHA/Views/IPD/AddEdit_GeneralDiagnosis.cshtml
@model AASTHA.Models.AdminModel

@{
    Layout = null;
}

<!DOCTYPE html>

<html>

<body>
    @using (Ajax.BeginForm("AddEdit_GeneralDiagnosis", "IPD", new AjaxOptions { UpdateTargetId = "Grid_General", OnBegin = "blockui_rightgrid", OnComplete = "unblockui_rightgrid", OnSuccess = "OnSuccess" }))
    {
        @Html.HiddenFor(m => m.page)
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <div class="input-group"> @Html.TextBoxFor(model => model.General_Diagnosis, new { @class = "form-control Capitalize", placeholder = "Enter General Diagnosis Title" }) <span class="input-group-btn"> <input class="btn btn-primary btnadd" type="submit" value="Save Changes"></span> </div>
                    @Html.ValidationMessageFor(m => m.General_Diagnosis)
                </div>
            </div>
        </div>
    }
</body>
</html>

AASTHA/Views/IPD/AdviceGrid.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<AASTHA.Models.tbl_advice>
@{
    Layout = null;
}
<div class="blockui_leftgrid">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>
                    No.
                </th>
                <th>
                    Advice Title
                </th>
                <th>Action</th>
            </tr>
        </thead>
        @foreach (var item in Model.Select((x, i) => new { Data = x, Index = i }))
        {
            <tr>
                <td>
                    @(item.Index + ((Model.PageNumber - 1) * Model.PageSize) + 1)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Data.Advice_Text)
                </td>
                <td>
                    @Ajax.ActionLink("Edit", "AddEdit_Advice", "IPD", new { id = item.Data.Id, page = Request.QueryString["page"] }, new AjaxOptions { UpdateTargetId = "AddEdit_Advice", OnBegin = "", OnComplete = "" }, new { @class = "btn btn-info btn-sm" })
                    @Ajax.ActionLink("Delete", "Delete_Advice", "IPD", new { id = item.Data.Id, page = Request.QueryString["page"] }, new AjaxOptions { UpdateTargetId = "Grid_Advice", OnBegin = "blockui_leftgrid", OnComplete = "unblockui_leftgrid", Confirm = "Are you sure to delete" }, new { @class = "btn btn-danger btn-sm" })
                </td>
            </tr>
        }
    </table>    
</div>
@if (Model.PageCount > 1)
{
    @Html.PagedListPager(Model, page => Url.Action("AdviceeGrid", new { page }), PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(new AjaxOptions { UpdateTargetId = "Grid_Advice" }))
}
<div>@ViewBag.records Records</div>

AASTHA/Views/IPD/Charge_Detail.cshtml
<div class="modal fade" id="detail-modal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">IPD Patient's Details</h4>
            </div>
            <div class="modal-body">
              
            </div>

        </div>
    </div>
</div>

<script>
   
</script>

AASTHA/Views/IPD/Edit_IPD.cshtml
@model AASTHA.Models.IPDModel


<link href="~/Content/css/Gujarati_Invoice_Style.css" rel="stylesheet" />
<link rel="stylesheet" href="~/Content/js/select2/select2-bootstrap.css" id="style-resource-1">
<link rel="stylesheet" href="~/Content/js/selectboxit/jquery.selectBoxIt.css" id="style-resource-3">
<link rel="stylesheet" href="~/Content/js/select2/select2.css" id="style-resource-2">
<link href="~/Content/css/bootstrap-multiselect.css" rel="stylesheet" />

<script src="~/Content/js/bootstrap-datepicker.js"></script>

<script src="~/Content/js/bootstrap-timepicker.min.js"></script>
<div class="modal fade" id="edit-modal">
    <div class="modal-dialog" style="width:1000px">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">IPD Patient's Details</h4>
            </div>

            @using (Ajax.BeginForm("Modal_Edit", "IPD", new AjaxOptions { OnSuccess = "editsuccess", }))
            {
            @Html.HiddenFor(m => m.Get_View)

            <div class="modal-body">
                <div class="row">
                    <div class="col-md-2">
                        <div class="form-group">
                            <label class="control-label" for="about">Invoice No.</label>
                            @Html.TextBoxFor(m => m.IPD_Id_Edit, new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.IPD_Id_Edit)
                        </div>
                    </div>
                    <div class="col-md-4 selectContainer">
                        <div class="form-group">
                            <label class="control-label" for="full_name">Full Name</label>
                            <select class="select2" data-allow-clear="true" data-placeholder="Select Patient" id="Patient_Id" name="Patient_Id" required>
                                <option></option>
                            </select>
                            @Html.ValidationMessageFor(m => m.Patient_Id)
                        </div>
                    </div>
                </div>
                <div class="row">

                    <div class="col-md-3 ">
                        <div class="form-group">
                            <label class="control-label" for="about">Room Type</label>
                            @Html.DropDownListFor(m => m.Room_Type, Model.Room_Type_List, "Select ", new { @class = "selectboxit" })
                            @Html.ValidationMessageFor(m => m.Room_Type)
                        </div>
                    </div>
                    <div class="col-md-3 selectContainer">
                        <div class="form-group">
                            <label for="field-4" class="control-label">Addmission Date</label>
                            <div class="input-group">
                                @Html.TextBoxFor(m => m.Addmission_Date, new { @class = "form-control datepicker", placeholder = "Enter Date" })
                                <div class="input-group-addon"> <a href="#"><i class="entypo-calendar"></i></a> </div>
                            </div>
                            @Html.ValidationMessageFor(m => m.Addmission_Date)
                        </div>
                    </div>
                    <div class="col-md-3 ">
                        <div class="form-group">
                            <label class="control-label" for="about">IPD Type</label>
                            @Html.DropDownListFor(m => m.IPD_Type, Model.IPD_Type_List, "Select ", new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.IPD_Type)
                        </div>
                    </div>
                    <div class="col-md-3 selectContainer">
                        <div class="form-group">
                            <label class="control-label" for="full_name">Discharge Date</label>
                            <div class="input-group">
                                @Html.TextBoxFor(m => m.Discharge_Date, new { @class = "form-control datepicker", placeholder = "Enter Date" })
                                <div class="input-group-addon"> <a href="#"><i class="entypo-calendar"></i></a> </div>
                            </div>
                            @Html.ValidationMessageFor(m => m.Discharge_Date)
                        </div>
                    </div>
                </div>
                <div id="Delivery">
                    <div class="row">
                        <div class="col-md-4 selectContainer">
                            <div class="form-group">
                                <label class="control-label" for="full_name">Delivery Date</label>
                                <div class="input-group">
                                    @Html.TextBoxFor(m => m.Delivery_Date, new { @class = "form-control datepicker", placeholder = "Enter Date" })
                                    <div class="input-group-addon"> <a href="#"><i class="entypo-calendar"></i></a> </div>
                                </div>
                                @Html.ValidationMessageFor(m => m.Delivery_Date)
                            </div>
                        </div>
                        <div class="col-md-4 selectContainer">
                            <div class="form-group">
                                <label for="field-4" class="control-label">Delivery Time</label>
                                <div class="input-group">
                                    @Html.TextBoxFor(m => m.Delivery_Time, new { @class = "form-control timepicker" })
                                    @*<input type="text" class="form-control timepicker" data-template="dropdown" data-show-seconds="true" data-default-time="11:25 AM" data-show-meridian="true" data-minute-step="5" data-second-step="5">*@
                                    <div class="input-group-addon"> <a href="#"><i class="entypo-clock"></i></a> </div>
                                </div>
                                @Html.ValidationMessageFor(m => m.Delivery_Time)
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="field-4" class="control-label">Type of Delivery</label><br />
                                @Html.DropDownListFor(m => m.Delivery_Type, Model.Delivery_Type_List, new { @class = "multiselect", multiple = "multiple", name = "type" })
                                @Html.ValidationMessageFor(m => m.Delivery_Type)
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label class="control-label" for="about">Diagnosis</label>
                                @Html.DropDownListFor(m => m.Delivery_Diagnosis, Model.Delivery_Diagnosis_List, "Select", new { @class = "selectboxit" })
                                @Html.ValidationMessageFor(m => m.Delivery_Diagnosis)
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="field-4" class="control-label">Baby Gender</label>
                                @Html.DropDownListFor(m => m.Baby_Gender, Model.Baby_Gender_List, "Select", new { @class = "selectboxit" })
                                @Html.ValidationMessageFor(m => m.Baby_Gender)
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="field-4" class="control-label">Baby Weight</label>
                                @Html.TextBoxFor(m => m.Baby_Weight, new { @class = "form-control" })
                                @Html.ValidationMessageFor(m => m.Baby_Weight)
                            </div>
                        </div>
                    </div>
                </div>
                <div id="Operation">
                    <div class="row">
                        <div class="col-md-4 selectContainer">
                            <div class="form-group">
                                <label class="control-label" for="about">Operation Date</label>
                                @Html.TextBoxFor(m => m.Operation_Date, new { @class = "form-control datepicker", placeholder = "Enter Date" })
                                @Html.ValidationMessageFor(m => m.Operation_Date)
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="field-4" class="control-label">Diagnosis</label><br />
                                @Html.DropDownListFor(m => m.Operation_Diagnosis, Model.Operation_Diagnosis_List, new { @class = "multiselect", multiple = "multiple" })
                                @Html.ValidationMessageFor(m => m.Operation_Diagnosis)
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="field-4" class="control-label">Operation Type</label><br />
                                @Html.DropDownListFor(m => m.Operation_Type, Model.Operation_Type_List, new { @class = "multiselect", multiple = "multiple" })
                                @Html.ValidationMessageFor(m => m.Operation_Type)
                            </div>
                        </div>
                    </div>
                </div>
                <div id="General">
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label class="control-label" for="about">Diagnosis</label><br />
                                @Html.DropDownListFor(m => m.General_Diagnosis, Model.General_Diagnosis_List, new { @class = "multiselect", multiple = "multiple" })
                                @Html.ValidationMessageFor(m => m.General_Diagnosis)
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div id="Charges" class="col-lg-12">

                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save changes</button>
                </div>
            </div>
            }
        </div>
    </div>
</div>


<script src="~/Scripts/MvcFoolproofJQueryValidation.min.js"></script>
<script src="~/Scripts/MvcFoolproofValidation.min.js"></script>
<script src="~/Scripts/mvcfoolproof.unobtrusive.min.js"></script>
<script>
    
    $(document).ready(function () {
        $("#Delivery").hide();
        $("#Operation").hide();
        $("#General").hide();

        $("select").change(function () {
            $(this).valid();
        });


        $('.multiselect').multiselect({
            buttonWidth: '100%',
        });

        $("#Addmission_Date").change(function () {
            $(this).valid();
        })
        $("#Discharge_Date").change(function () {
            $(this).valid();
        })
        $("#Delivery_Date").change(function () {
            $(this).valid();
        })
        $("#Delivery_Time").change(function () {
            $(this).valid();
        })
        $("#Operation_Date").change(function () {
            $(this).valid();
        })
        $("#Delivery_Diagnosis").change(function () {
            $(this).valid();
        })
        $("#Baby_Gender").change(function () {
            $(this).valid();
        })
        $('.timepicker').timepicker({
            showInputs: false,
            minuteStep: 1
        });
        $('.modal').on('hidden.bs.modal', function () {
            resetform();
            resetselect2();
            resetselectboxit();
            resetValidation();
            resetmultiselect();
        });

        $('.modal').on('shown.bs.modal', function () {
            resetValidation();
        })

    })
    function editsuccess() {
        $("#edit-modal").modal('hide');
        $("#ipd_table").dataTable().fnDraw();
    }

</script>

AASTHA/Views/IPD/GeneralDiagnosisGrid.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<AASTHA.Models.general_diagnosis>

@{
    Layout = null;
}
<div class="blockui_rightgrid">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>
                    No.
                </th>
                <th>
                    General Diagnosis Title
                </th>
                <th width="150px">Action</th>
            </tr>
        </thead>

        @foreach (var item in Model.Select((x, i) => new { Data = x, Index = i }))
        {
            <tr>
                <td>
                    @(item.Index + ((Model.PageNumber - 1) * Model.PageSize) + 1)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Data.general_diagnosis_name)
                </td>
                <td>
                    @Ajax.ActionLink("Edit", "AddEdit_GeneralDiagnosis", "IPD", new { id = item.Data.general_diagnosis_Id, page = Request.QueryString["page"] }, new AjaxOptions { UpdateTargetId = "AddEdit_General", }, new { @class = "btn btn-info btn-sm" })
                    @Ajax.ActionLink("Delete", "Delete_GeneralDiagnosis", "IPD", new { id = item.Data.general_diagnosis_Id, page = Request.QueryString["page"] }, new AjaxOptions { UpdateTargetId = "Grid_General", OnBegin = "blockui_rightgrid", OnComplete = "unblockui_rightgrid", Confirm = "Are you sure to delete" }, new { @class = "btn btn-danger btn-sm" })
                </td>
            </tr>
        }
    </table>
</div>
@if (Model.PageCount > 1)
{
    @Html.PagedListPager(Model, page => Url.Action("GeneralDiagnosisGrid", new { page }), PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(new AjaxOptions { UpdateTargetId = "Grid_General", OnBegin = "blockui_rightgrid", OnComplete = "unblockui_rightgrid", OnSuccess = "OnSuccess" }))
}

AASTHA/Views/IPD/Manage_DeliveryType.cshtml
@{
    ViewBag.Title = "Manage_DeliveryType";
    Layout = null;
}
<div class="panel panel-primary" data-collapsed="0">
    <div class="panel-heading">
        <div class="panel-title">
            Manage Delivery Type
        </div> <div class="panel-options"> <a href="#sample-modal" data-toggle="modal" data-target="#sample-modal-dialog-1" class="bg"><i class="entypo-cog"></i></a> <a href="#" data-rel="collapse"><i class="entypo-down-open"></i></a> <a href="#" data-rel="reload"><i class="entypo-arrows-ccw"></i></a> <a href="#" data-rel="close"><i class="entypo-cancel"></i></a> </div>
    </div> <div class="panel-body">
        <div class="row">
            <div class="col-lg-12" id="AddEdit_Delivery">
                @Html.Action("AddEdit_DeliveryType", "IPD")
            </div>
            <div class="col-lg-12" id="Grid_Delivery">
                @Html.Action("DeliveryTypeGrid", "IPD")
            </div>
        </div>

    </div>
</div>

AASTHA/Views/IPD/Manage_GeneralDiagnosis.cshtml
@{
    ViewBag.Title = "Manage_DeliveryType";
    Layout = null;
}

<div class="panel panel-primary" data-collapsed="0">
    <div class="panel-heading">
        <div class="panel-title">
            Manage General Diagnosis
        </div> <div class="panel-options"> <a href="#sample-modal" data-toggle="modal" data-target="#sample-modal-dialog-1" class="bg"><i class="entypo-cog"></i></a> <a href="#" data-rel="collapse"><i class="entypo-down-open"></i></a> <a href="#" data-rel="reload"><i class="entypo-arrows-ccw"></i></a> <a href="#" data-rel="close"><i class="entypo-cancel"></i></a> </div>
    </div> <div class="panel-body">
        <div class="row">
            <div class="col-lg-12" id="AddEdit_General">
                @Html.Action("AddEdit_GeneralDiagnosis", "IPD")
            </div>
            <div class="col-lg-12" id="Grid_General">
                @Html.Action("GeneralDiagnosisGrid", "IPD")
            </div>
        </div>

    </div>
</div>

AASTHA/Views/IPD/Manage_OperationDiagnosis.cshtml
@{
    ViewBag.Title = "Manage_DeliveryType";
    Layout = null;
}
<div class="panel panel-primary" data-collapsed="0">
    <div class="panel-heading">
        <div class="panel-title">
            Manage Operation Diagnosis
        </div> <div class="panel-options"> <a href="#sample-modal" data-toggle="modal" data-target="#sample-modal-dialog-1" class="bg"><i class="entypo-cog"></i></a> <a href="#" data-rel="collapse"><i class="entypo-down-open"></i></a> <a href="#" data-rel="reload"><i class="entypo-arrows-ccw"></i></a> <a href="#" data-rel="close"><i class="entypo-cancel"></i></a> </div>
    </div> <div class="panel-body">
        <div class="row">
            <div class="col-lg-12" id="AddEdit_Operation">
                @Html.Action("AddEdit_OperationDiagnosis", "IPD")
            </div>
            <div class="col-lg-12" id="Grid_Operation">
                @Html.Action("OperationDiagnosisGrid", "IPD")
            </div>
        </div>

    </div>
</div>